language: ruby
os: linux
dist: bionic
rvm:
- 2.6.5
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
cache: bundler
deploy:
  provider: surge
  project: "./_site/"
  domain: "$SURGE_DOMAIN"
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: XiPqA2a1hXWUzCgHVnAd65qNg9Tu3VYj+A4hgDrRzIu7gZ3xcSUAzmZ3Az6RdsXulJb5aC6QqxQKQNa4fjCBC2/TMawbR8qxrMzEyyaYPr/Kc+P7boZz2Xw9ESh1lgLD5QCYSE0k5QMMr//7mKnB9u6IsRFArTz6pD4XKwsRpC8QVRM3hxt/zSHRppdnpggDly9Sx2acFiW9ksYJGP0RGLoemoK2THNX9rv0dxBMWhmafKDvk8ToK4nKzDjw/vGVrFQ0Ybmcb+B89VqUV13xb/0sAUEVmJtabeMQAygnCS7rwy1kAdHJhRqwkol3Ou3fKuWaHe8xmVj+qKzjFmayyU2vZMt1NwzVLmJoCiRY2YnMXKKie7t2wscfuhpZUdCVW+G+vBZvtH6iuKkC3gmMN6FlcqS+YKrCKJ7L1S1XRU5Dntt7ATVLD9MhMl2XaeOdU+CszbJiCWDX6tpItLBvvD4TTFIG46nlpGHTPJ9tq/PIUtcnL9lEYg0oaF3/p73b+yCjQRJ0V1Bo/DrgStd07TmxZb4nNzfQcs/gGD20u6G5dhFcbzEIhdXsS8izxXsH5BoZaTONEfS7dTHNfJeCgVa6viO1VYMYIobYCPp4xzWHfZx0aWgLFae7/MEDDdgEyUpHG2I20JrtSoGr3mm2phbknC/3YgRgUUtEs8SUBOE=
