collections:
  authors:
    output: true
    permalink: /staff/:path/

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      order: 100
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed
